[Task-48] Added filters for recruitment list
cometio-solutions/recio-frontend pull request #16
Opened 2021-04-22 18:41 UTC by skusnierz

2021-04-22 18:48 UTC, twrdyyy approved these changes

2021-04-22 19:59 UTC, jmysliv requested changes

2021-04-22 19:59 UTC, jmysliv commented on src/services/api.ts
> +const API_URL = 'http://localhost:5000';
Change it back to our backend api's ip.

2021-04-22 20:15 UTC, szebniok approved these changes

2021-04-23 08:35 UTC, jmysliv approved these changes

2021-04-23 08:37 UTC, merged